# Generated by Django 2.2.4 on 2019-08-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShortener', '0002_auto_20190813_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_urls',
            old_name='short_urls',
            new_name='short_url',
        ),
    ]
